services:
  video2emotion:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    
    # Example command - override with your own
    # command: python main.py --input_dir=/app/videos --frames_dir=/app/frames --output_dir=/app/output